plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gozcuradar.v1'
    compileSdk 35

    signingConfigs {
        release {
            storeFile file("gozcu-radar.keystore")
            storePassword "Totik01*"
            keyAlias "gozcuradar"
            keyPassword "Totik01*"
        }
    }

    defaultConfig {
        applicationId "com.gozcuradar.v1"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'org.maplibre.gl:android-sdk:11.8.0'
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}
