plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.siberradar.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.siberradar.app"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../siber-radar-release.jks")
            storePassword "Totik01*"
            keyAlias "siber-radar"
            keyPassword "Totik01*"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
}
