name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Android tools
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip
        yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
        sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0" \
          "build-tools;37.0.0"
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Install Buildozer
      run: |
        pip install --user buildozer cython==0.29.36
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build APK
      working-directory: apk_siber_radar
      run: |
        rm -rf .buildozer
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: siber-radar-apk
        path: apk_siber_radar/bin/*.apk
