name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup system
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-venv \
            git \
            zip \
            unzip \
            openjdk-17-jdk

      - name: Setup Python
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Build APK
        working-directory: apk_siber_radar
        run: |
          ../venv/bin/pip install cython==0.29.36
          export PATH=$PWD/../venv/bin:$PATH
          ../venv/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: siber-radar-apk
          path: apk_siber_radar/bin/*.apk
