name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip
          python -m pip install --upgrade pip
          pip install --user buildozer cython==0.29.36
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        working-directory: apk_siber_radar
        run: |
          yes | buildozer android clean || true
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: siber-radar-apk
          path: apk_siber_radar/bin/*.apk
